INSERT INTO skill(title, created_at, updated_at)
VALUES
    ('Java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SQL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('C++', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('leadership', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('C#', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);