INSERT INTO user_skill(user_id, skill_id, created_at, updated_at)
VALUES
    (1,1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10,1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7,1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2,1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8,1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);